---
title: "eda"
author: "Nicole Criscuolo"
date: "2025-10-02"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Import weather data.
```{r}
data("weather_df")

weather_df =
  weather_df |> 
  mutate(month = floor_date(date, unit = "month"))
```

```{r}
weather_df |> 
  ggplot(aes(x=prcp)) +
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp > 1000)
```

Look at data again.
```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```

## Add groups.

```{r}
weather_df |> 
  group_by(name, month)
```

Group and count thigns.
```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n = n()
  )
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    n = n_distinct(date)
  )
```

You can count directly. 
```{r}
weather_df |> 
  count(name)
```

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), #na.rm removes NA values
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

This is still a data frame.
```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

Sometimes format for human readability
```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```

## Mutate with groups
```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    center_tmax = tmax - mean_tmax
  ) |> 
  ggplot(aes(x = date, y = center_tmax, color = name)) + 
  geom_point()
```

Look for hot days.
```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(temp_rank = min_rank(desc(tmax))) |> # min_rank ranks from minimum to maximum
  filter(temp_rank < 2)
```

What about lags? Order of data matters here b/c pulling data from previous row
```{r}
weather_df |> 
  group_by(name) |> # keeps track of names so that when name changes for each location the first row for jan 01 is NA bc no obs for that group for the day before
  mutate(lagged_tmax = lag(tmax)) # what happened yesterday
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax) 
  ) |> 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE),
    tmax_change_max = max(temp_change, na.rm = TRUE)
  )
```

Determine which day had largest temp change
```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax)
  ) |> 
  filter(
    min_rank(desc(temp_change)) < 2
  )
```

## Revisit pulse from visualization ii
```{r}
pulse_df =
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |> 
  mutate(visit = fct_inorder(visit)) # in order they appear in data set

pulse_df |> 
  ggplot(aes(x = visit, y = bdi)) +
  geom_boxplot()

pulse_df |> 
  group_by(visit) |> 
  summarize(
    mean_bdi = mean(bdi, na.rm = TRUE),
    median_bdi = median(bdi, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```



